# Production overrides
services:
  web:
    labels:
      caddy: {{domain}}
      caddy.reverse_proxy: "{{upstreams 80}}"
    networks:
      - caddy-network

networks:
  caddy-network:
    external: true