services:
  web:
    image: nginx:alpine
    restart: unless-stopped
    stop_grace_period: 1s
    volumes:
      - ../dist:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro